version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Amazon-S3-Bucket-Load-Test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9uezuy1wn7v6"
s3_prefix = "Amazon-S3-Bucket-Load-Test"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VpcCidrBlock=192.168.0.0/16 SubnetACidrBlock=192.168.0.0/20 SubnetBCidrBlock=192.168.16.0/20 EgressCidr=0.0.0.0/0"

